apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-pv
  labels:
    type: volumes
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
