apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    type: volume-claim
spec:
  volumeName: minikube-pv
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi